[tool.poetry]
name = "fpm-py"
version = "0.0.1"
description = ""
authors = ["Robin Cunningham <rspcunningham@gmail.com>", "Sammy Farnum <sfarnum1132@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
